# Generated by Django 2.2.18 on 2025-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0060_auto_20240302_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedlabel',
            name='code',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
